server:
  port: 8761   # default Eureka server port

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false   # server should not register itself
    fetch-registry: false         # server should not fetch registry
