server:
  port: 8083

spring:
  application:
    name: trigger-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mnp
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:"

# Eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

# Resilience4j basic config
resilience4j:
  circuitbreaker:
    instances:
      providerNotify:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
  retry:
    instances:
      providerNotify:
        maxAttempts: 3
        waitDuration: 1s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

security:
  shared-secret: changeme
debug: true