server:
  port: 8084   # Changed from 8080 to 8084

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: portability-request-service
          uri: lb://portability-request-service
          predicates:
            - Path=/requests/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
